trigger:
  branches:
    include:
      - development

pool:
  name: your-agent-name
  demands:
    - agent.name -equals node-name

variables:
  imageName: 'registry.gitlab.com/gitlab-user-name/project-name'
  dockerFilePath: 'Dockerfile'
  publishDir: '$(Build.ArtifactStagingDirectory)'
  GITLAB_REGISTRY_USER: 'user-name' 
  GITLAB_REGISTRY_PASSWORD: 'user-password or key'

steps:
- bash: |
    echo -e "Subject: Deployment Başladı\n\nDeployment başladı: Branch=$(Build.SourceBranchName), Commit=$(Build.SourceVersion)" | msmtp example@email.com
  displayName: 'Send mail (Start)'
  condition: always()

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- bash: |
    # Build the project
    dotnet build your-path-csproj --configuration Release
  displayName: 'Build Project'

- bash: |
    # Publish the project
    dotnet publish your-path-csproj --configuration Release --output $(publishDir)
  displayName: 'Publish Project'

- bash: |
    # Create image tag in the format: year-month-day-hour:minute-commitId
    TAG=$(date +"%Y-%m-%d-%H.%M")-$(echo $(Build.SourceVersion) | cut -c1-7)
    echo "Generated image tag: $TAG"
    echo "##vso[task.setvariable variable=imageTag]$TAG"
  displayName: 'Generate Image Tag'

- bash: |
    # Build the Docker image
    docker build --no-cache -t $(imageName):$(imageTag) -f $(dockerFilePath) .
  displayName: 'Build Docker Image'

- bash: |
    trivy image --severity HIGH,CRITICAL --exit-code 0 --timeout 10m --scanners vuln --format json --output trivy-report.json $(imageName):$(imageTag)
  displayName: 'Scan Docker Image with Trivy'
  continueOnError: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'trivy-report.json'
    artifact: 'TrivyReport'
  displayName: 'Publish Trivy Report'

- bash: |
    trivy image --severity HIGH,CRITICAL --exit-code 0 $(imageName):$(imageTag)
  displayName: 'Report Write to Console'

- bash: |
    # Log in to GitLab Container Registry
    echo $(GITLAB_REGISTRY_PASSWORD) | docker login registry.gitlab.com -u $(GITLAB_REGISTRY_USER) --password-stdin
  displayName: 'Login to GitLab Container Registry'

- bash: |
    # Push Docker image to GitLab Container Registry
    docker push $(imageName):$(imageTag)
  displayName: 'Push Docker Image to GitLab Container Registry'

- bash: |
    # Update docker-compose.yml with dynamic tag
    sed -i "s|registry.gitlab.com/user-name/project-name:.*|registry.gitlab.com/user-name/project-name:$(imageTag)|g" your-path.yml
  displayName: 'Update Docker Compose with Dynamic Tag'

- bash: |
    # Deploy to Docker Swarm
    docker stack deploy --compose-file your-path.yml blazor-dbmigrator
  displayName: 'Deploy to Docker Swarm'

- bash: |
    echo -e "Subject: Deployment Tamamlandı\n\nDeployment Başarıyla Tamamlandı: Branch=$(Build.SourceBranchName), Commit=$(Build.SourceVersion)" | msmtp example@email.com
  displayName: 'Send mail (Finish)'
  condition: succeeded()

- bash: |
    echo -e "Subject: HATA!\n\nDeployment Başarısız: Branch=$(Build.SourceBranchName), Commit=$(Build.SourceVersion)" | msmtp example@email.com
  condition: failed()