version: "3.9"
services:

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=your-email
      - GF_SMTP_PASSWORD=your-email-password or key
      - GF_SMTP_FROM_ADDRESS=your-email
      - GF_SMTP_STARTTLS_POLICY=Require
    user: root
    volumes:
      - grafanadata:/var/lib/grafana
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure 
      placement:
        constraints: [node.hostname == node-name]

networks:
  frontend:
    external: true

volumes:
  grafanadata: