version: "3.9"
services:
  healtcare-blazor:
    image: registry.gitlab.com/berkmkaracayir/pusula:${imageTag}
    ports: 
      - "9005:80"
    environment:
      - ConnectionStrings__Default=Host=64.226.68.43;Port=5432;Database=HealthCare;User ID=postgres;Password=myPassw0rd;
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Istanbul
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - db-migrator
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism:
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role==manager]

networks:
  frontend:
    external: true
