version: "3.9"
services:
  healtcare-blazor:
    image: registry.gitlab.com/berkmkaracayir/pusula:${imageTag}
    ports: 
      - "9005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Istanbul
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - db-migrator
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role==manager]
      labels:
        - "traefik.docker.network=frontend"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefix:/hello;"
        - "traefik.backend.loadbalancer.sticky=true"
 
  loadbalancer:
    image: traefik
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --web \
      --loglevel=DEBUG
    ports:
      - 80:80
      - 25581:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
         constraints: [node.role == manager]
    networks:
      - frontend
networks:
  frontend:
    external: true
