version: "3.9"
services:
  healtcare-blazor:
    image: registry.gitlab.com/berkmkaracayir/pusula:${imageTag}
    ports: 
      - "9005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Istanbul
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - db-migrator
    networks:
      - frontend
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthcare-blazor.rule=Host(`team3-pusula-healthcare.pusulayazilim.com.tr`)"
      - "traefik.http.services.healthcare-blazor.loadbalancer.server.port=80"
      - "traefik.http.routers.healthcare-blazor.entrypoints=websecure"
      - "traefik.http.routers.healthcare-blazor.tls=true"
      - "traefik.http.routers.healthcare-blazor.tls.certresolver=myresolver"
      - "traefik.http.services.healthcare-blazor.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.healthcare-blazor.loadbalancer.sticky.cookie.name=healthcare_blazor_session"

networks:
  frontend:
    external: true
