version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassw0rd
      POSTGRES_DB: HealthCare
      TZ: Europe/Istanbul
    ports:
      - "5432:5432"
    networks:
      - frontend
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=250'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    deploy:
      restart_policy:
        condition: on-failure     
      placement:
        constraints: [node.hostname == team3-node1]

networks:
  frontend:
    external: true

volumes:
  postgresdb-data:
