trigger:
  branches:
    include:
      - development

pool:
  name: pusula-akademi-team3-agent
  demands:
    - agent.name -equals team3-node1

variables:
  SONARQUBE_ENDPOINT: 'http://64.226.68.43:9000'
  SONARQUBE_PROJECT_KEY: 'Pusula.Training.HealthCare.Team3_Pusula.Training.HealthCare_AZPqdOnHHu30eRZfQ0dT'
  SONARQUBE_PROJECT_NAME: 'Pusula.Training.HealthCare'
  SONARQUBE_PROJECT_VERSION: '1.0'
  SONARQUBE_SERVICE_CONNECTION: 'Sonarqube'  

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: $(SONARQUBE_SERVICE_CONNECTION)   
    scannerMode: 'MSBuild'
    projectKey: $(SONARQUBE_PROJECT_KEY)
    projectName: $(SONARQUBE_PROJECT_NAME)
    projectVersion: $(SONARQUBE_PROJECT_VERSION)

- script: |
    # Build the project for analysis
    dotnet build src/Pusula.Training.HealthCare.Blazor/Pusula.Training.HealthCare.Blazor.csproj --configuration Release
  displayName: 'Build Project'

- task: SonarQubeAnalyze@6
  inputs:
    SonarQube: $(SONARQUBE_SERVICE_CONNECTION)  

- task: SonarQubePublish@6
  inputs:
    SonarQube: $(SONARQUBE_SERVICE_CONNECTION)  
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube Results'
