version: "3.9"
services:
  rabbitmq-node-1:
    image: rabbitmq:management
    container_name: rabbitmq-node-1
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecurecookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "mypassword"
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node-1"
      RABBITMQ_USE_LONGNAME: "true"
    ports:
      - "5672:5672"    
      - "15672:15672"  
    networks:
      - frontend
    volumes:
      - rabbitmq-node-1-data:/var/lib/rabbitmq
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  rabbitmq-node-2:
    image: rabbitmq:management
    container_name: rabbitmq-node-2
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecurecookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "mypassword"
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node-2"
      RABBITMQ_USE_LONGNAME: "true"
      RABBITMQ_CLUSTER_NODES: "rabbit@rabbitmq-node-1"
    ports:
      - "5673:5672"    
      - "15673:15672"  
    networks:
      - frontend
    volumes:
      - rabbitmq-node-2-data:/var/lib/rabbitmq
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  rabbitmq-node-3:
    image: rabbitmq:management
    container_name: rabbitmq-node-3
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecurecookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "mypassword"
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node-3"
      RABBITMQ_USE_LONGNAME: "true"
      RABBITMQ_CLUSTER_NODES: "rabbit@rabbitmq-node-1"
    ports:
      - "5674:5672"    
      - "15674:15672"  
    networks:
      - frontend
    volumes:
      - rabbitmq-node-3-data:/var/lib/rabbitmq
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  frontend:
    external: true

volumes:
  rabbitmq-node-1-data:
  rabbitmq-node-2-data:
  rabbitmq-node-3-data:
