version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: c_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pusulateam3
      - RABBITMQ_ERLANG_COOKIE=pusulateam_cookie
      - RABBITMQ_NODENAME=rabbit@c_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - frontend
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure     
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
    external: true

volumes:
  rabbitmqdata:
