version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: c_elasticsearch
    environment:
      - xpack.watcher.enabled=false
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=1q2w3e*
    ports:
      - "9200:9200"
    networks:
      - frontend
    volumes:
     - esdata:/usr/share/elasticsearch/data
    deploy:
      restart_policy:
        condition: on-failure     
      placement:
        constraints: [node.hostname == team3-node2]

networks:
  frontend:
    external: true

volumes:
  esdata:
