version: "3.9"
services:
  redis-node-1:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - frontend
    environment:
      - REDIS_PASSWORD=pusulateam3node
    command: >
      redis-server --appendonly yes --requirepass pusulateam3node
      --masterauth pusulateam3node --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
      --port 6379
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    volumes:
      - redisdata-1:/data

  redis-node-2:
    image: redis:latest
    networks:
      - frontend
    environment:
      - REDIS_PASSWORD=pusulateam3node
    command: >
      redis-server --appendonly yes --requirepass pusulateam3node
      --masterauth pusulateam3node --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
      --port 6379
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    volumes:
      - redisdata-2:/data

  redis-node-3:
    image: redis:latest
    networks:
      - frontend
    environment:
      - REDIS_PASSWORD=pusulateam3node
    command: >
      redis-server --appendonly yes --requirepass pusulateam3node
      --masterauth pusulateam3node --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
      --port 6379
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    volumes:
      - redisdata-3:/data

  redis-node-4:
    image: redis:latest
    networks:
      - frontend
    environment:
      - REDIS_PASSWORD=pusulateam3node
    command: >
      redis-server --appendonly yes --requirepass pusulateam3node
      --masterauth pusulateam3node --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
      --port 6379
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    volumes:
      - redisdata-4:/data

  redis-node-5:
    image: redis:latest
    networks:
      - frontend
    environment:
      - REDIS_PASSWORD=pusulateam3node
    command: >
      redis-server --appendonly yes --requirepass pusulateam3node
      --masterauth pusulateam3node --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
      --port 6379
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    volumes:
      - redisdata-5:/data

  redis-node-6:
    image: redis:latest
    networks:
      - frontend
    environment:
      - REDIS_PASSWORD=pusulateam3node
    command: >
      redis-server --appendonly yes --requirepass pusulateam3node
      --masterauth pusulateam3node --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
      --port 6379
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    volumes:
      - redisdata-6:/data

networks:
  frontend:
    external: true

volumes:
  redisdata-1: {}
  redisdata-2: {}
  redisdata-3: {}
  redisdata-4: {}
  redisdata-5: {}
  redisdata-6: {}