version: "3.9"
services:
  db-migrator:
    image: registry.gitlab.com/berkmkaracayir/migrator:${imageTag}
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=HealthCare;User ID=postgres;Password=myPassw0rd;
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - frontend
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role==manager]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthcare-blazor.rule=Host('team3-pusula-healthcare.pusulayazilim.com.tr')"
      - "traefik.http.services.healthcare-blazor.loadbalancer.server.port=80"
      - "traefik.http.routers.healthcare-blazor.entrypoints=websecure"
      - "traefik.http.routers.healthcare-blazor.tls=true"
      - "traefik.http.routers.healthcare-blazor.tls.certresolver=myresolver"
      - "traefik.http.services.healthcare-blazor.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.healthcare-blazor.loadbalancer.sticky.cookie.name=healthcare_blazor_session"

networks:
  frontend:
    external: true
