version: "3.9"
services:
  db-migrator:
    image: registry.gitlab.com/berkmkaracayir/migrator:${imageTag}
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=HealthCare;User ID=postgres;Password=myPassw0rd;
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - frontend
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role==manager]

networks:
  frontend:
    external: true
